# Generated by Django 3.2.3 on 2021-05-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.IntegerField(max_length=50),
        ),
    ]
