# Generated by Django 3.1.7 on 2021-06-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0004_auto_20210601_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qty',
            field=models.FloatField(max_length=50),
        ),
    ]
