# Generated by Django 3.1.7 on 2021-06-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0006_auto_20210602_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customername',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
